### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jumsintheflow** [EmilAlipiev/XFInAppBilling#11]
I need your help please.
I can buy/purchase successfully Google Play dialog closes without any problems, BUT app crashes when I exit Google Play billing dialog without buying (just taping back button or cliking outside the dialog)

var billing = CrossXFInAppBilling.Current;
            try
            {
                connected = await CrossXFInAppBilling.Current.ConnectAsync();
                if (!connected)
                {
                    //Couldn't connect to billing
                    new AlertDialog.Builder(this) .SetPositiveButton("OK", (sender2, args) => { })  .SetMessage("\n" + "Couldn't connect to Google Play billing," + "\n")
                             .SetTitle("Error!")  .Show();
                    return;
                }
                //try to purchase item
                verify = new Verify();
                try
                {
                    purchase = await billing.PurchaseAsync(productid, ItemType.Subscription, null, null);

                    if (purchase == null)
                    {
                        //Not purchased, may also throw exception to catch
                        new AlertDialog.Builder(this)
                          .SetPositiveButton("OK", (sender2, args) => { })  .SetMessage("\n" + "Not purchased" + "\n")  .SetTitle("Error!")  .Show();

                        Toast.MakeText(ApplicationContext, "null", ToastLength.Long).Show();
                    }
                    else
                    {
                        //Purchased, save this information
            //            var id = purchasee.OrderId;
            //            var token = purchasee.PurchaseToken;
                        var state = purchase.PurchaseState;
                        

                        Toast.MakeText(ApplicationContext, state.ToString() + kjkjk, ToastLength.Long).Show();
                    }
                }
                catch (System.NullReferenceException nall)
                {
                    Console.WriteLine("Reference Exception: " + nall);
                    billing.Disconnect();
                } 
                Toast.MakeText(ApplicationContext, "ppp", ToastLength.Long).Show();                
            }
            catch (InAppBillingPurchaseException purchaseEx)  // Plugin.InAppBilling.InAppBillingPurchaseException: 
            {
                Console.WriteLine("Issue: " + purchaseEx);
                var message = string.Empty;
                switch (purchaseEx.PurchaseError)
                {
                    case PurchaseError.AppStoreUnavailable:
                        message = "Currently the Google Play store seems to be unavailble. Try again later.";
                        Toast.MakeText(ApplicationContext, message, ToastLength.Long).Show();
                        break;
                    case PurchaseError.BillingUnavailable:
                        message = "Billing seems to be unavailable, please try again later.";
                        Toast.MakeText(ApplicationContext, message, ToastLength.Long).Show();
                        break;
                    case PurchaseError.PaymentInvalid:
                        message = "Payment seems to be invalid, please try again.";
                        Toast.MakeText(ApplicationContext, message, ToastLength.Long).Show();
                        break;
                    case PurchaseError.PaymentNotAllowed:
                        message = "Payment does not seem to be enabled/allowed, please try again.";
                        Toast.MakeText(ApplicationContext, message, ToastLength.Long).Show();
                        break;
                    default:
                        Toast.MakeText(ApplicationContext, purchaseEx.InnerException.ToString(), ToastLength.Long).Show();
                        break;
                }

                //Decide if it is an error we care about
                if (string.IsNullOrWhiteSpace(message))
                    return;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Issue connecting: " + ex);
                Toast.MakeText(ApplicationContext, ex.InnerException.ToString(), ToastLength.Long).Show();
            }
            finally
            {
                //Disconnect, it is okay if we never connected, this will never throw an exception
                billing.Disconnect();
            }

09-05 12:28:52.232 W/ProxyBillingActivity(10950): Activity finished with resultCode 0 and billing's responseCode: 1
09-05 12:28:52.274 D/ZrHung.AppEyeUiProbe(10950): restart watching
09-05 12:28:52.284 W/BillingHelper(10950): Couldn't find purchase lists, trying to find single data.
09-05 12:28:52.284 W/BillingHelper(10950): Received a bad purchase data.
09-05 12:28:52.285 W/BillingHelper(10950): Couldn't find single purchase data as well.
09-05 12:28:52.292 D/Mono    (10950): Requesting loading reference 6 (of 7) of /storage/emulated/0/Android/data/com.appsjooms.gainpamore/files/.__override__/XFInAppBilling.dll
09-05 12:28:52.292 D/Mono    (10950): Loading reference 6 of /storage/emulated/0/Android/data/com.appsjooms.gainpamore/files/.__override__/XFInAppBilling.dll asmctx DEFAULT, looking for System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
09-05 12:28:52.292 D/Mono    (10950): Assembly Ref addref XFInAppBilling[0x7090544900] -> System.Core[0x70aad20e00]: 4
09-05 12:28:52.359 I/mono-stdout(10950): Issue: Plugin.XFInAppBilling.InAppBillingPurchaseException: Unable to process purchase.
Issue: Plugin.XFInAppBilling.InAppBillingPurchaseException: Unable to process purchase.
  at Plugin.XFInAppBilling.XFInAppBillingImplementation.DoPurchaseAsync (Android.BillingClient.Api.SkuDetails product) [0x000d9] in D:\a\XFInAppBilling\XFInAppBilling\XFInAppBilling\XFInAppBilling.android.cs:301 
  at Plugin.XFInAppBilling.XFInAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.XFInAppBilling.ItemType itemType, System.String payload, Plugin.XFInAppBilling.IInAppBillingVerifyPurchase verifyPurchase) [0x000ad] in D:\a\XFInAppBilling\XFInAppBilling\XFInAppBilling\XFInAppBilling.android.cs:166 
09-05 12:28:52.361 I/mono-stdout(10950):   at Plugin.XFInAppBilling.XFInAppBillingImplementation.DoPurchaseAsync (Android.BillingClient.Api.SkuDetails product) [0x000d9] in D:\a\XFInAppBilling\XFInAppBilling\XFInAppBilling\XFInAppBilling.android.cs:301 
09-05 12:28:52.361 I/mono-stdout(10950):   at Plugin.XFInAppBilling.XFInAppBillingImplementation.PurchaseAsync (System.String productId, Plugin.XFInAppBilling.ItemType itemType, System.String payload, Plugin.XFInAppBilling.IInAppBillingVerifyPurchase verifyPurchase) [0x000ad] in D:\a\XFInAppBilling\XFInAppBilling\XFInAppBilling\XFInAppBilling.android.cs:166 
  at Gainpamore.InAppActivity.Pabile (System.String productid) [0x0013a] in C:\Users\Username\Documents\Projects\Gainpamore Pro 1.1 xfinapp\Gainpamore\InAppActivity.cs:119 09-05 12:28:52.361 I/mono-stdout(10950):   at Gainpamore.InAppActivity.Pabile (System.String productid) [0x0013a] in C:\Users\Username\Documents\Projects\Gainpamore Pro 1.1 xfinapp\Gainpamore\InAppActivity.cs:119 

09-05 12:28:52.382 D/Mono    (10950): DllImport searching in: '__Internal' ('(null)').
09-05 12:28:52.382 D/Mono    (10950): Searching for 'java_interop_jnienv_call_nonvirtual_boolean_method_a'.
09-05 12:28:52.382 D/Mono    (10950): Probing 'java_interop_jnienv_call_nonvirtual_boolean_method_a'.
09-05 12:28:52.382 D/Mono    (10950): Found as 'java_interop_jnienv_call_nonvirtual_boolean_method_a'.
09-05 12:28:53.276 D/ZrHung.AppEyeUiProbe(10950): not watching, wait.
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

**Comment by EmilAlipiev** [comment]
I think that this is more related to your code. Library is throwing InAppBillingPurchaseException and i can see that you are already catching it fine but later probably you try to verify something is null in your ProxyBillingActivity. Probably you need to restructure this part.

**Comment by appsjooms** [comment]
yes indeed, problem is with my codes. thank for replying.

**Comment by EmilAlipiev** [comment]
I am closing this one. Please let me know in case if you still need help. thanks
