### ISSUE TITLE
System.NullReferenceException on _tcsPurchases (android)

### ISSUE THREAD

**Issue by Stratosf** [EmilAlipiev/XFInAppBilling#20]
Hello!
I am currently testing on Android. With the latest nugets I am getting a System.NullReferenceException the first time I call GetPurchasesAsync or CheckIfUserHasActiveSubscriptionAsync. It seems that _tcsPurchases is not initialized until OnQueryPurchasesResponse gets called. Any help is appreciated!

**Comment by Stratosf** [comment]
I see now it has been fixed in Billing221updateAndroidX so i am going to close this.

**Comment by EmilAlipiev** [comment]
yep, try the version 4.0.5. I have upgraded to Android Billing 4.0.0 version which is latest from google. Google has it in the release notes also that they fixed the memory leak issue which was crucial.
