### ISSUE TITLE
Crash on android, when the user taps the close button

### ISSUE THREAD

**Issue by Stratosf** [EmilAlipiev/XFInAppBilling#21]
With version 4.0.7 I have some weird crash on android, when the user taps the close button

<img src=https://user-images.githubusercontent.com/49019676/147251465-e24f2c3e-e2b8-40e7-95ae-fc5506f5a20d.jpg  height="600">

Am I doing something wrong? I am unable to catch an exception. Thanks in advance

**Comment by EmilAlipiev** [comment]
Do you see any crash report in your Appcenter or logging? Or you could reproduce yourself? I have just tried and debugged the behaviour and result lands OnPurchasesUpdated with purchases being null which is also handled with null check. For me it isnt crashing. Let me know if you can give me more information.

![image](https://user-images.githubusercontent.com/10422347/147390685-0342bc6c-a3d7-4942-aa6d-2452490cbb42.png)

**Comment by EmilAlipiev** [comment]
Closing this issue. if you still have similar issue please feel free to update with more information and reopen it.
