### ISSUE TITLE
Update to use newer version of the Amazon IAP SDK

### ISSUE THREAD

**Issue by shimfish** [EmilAlipiev/XFInAppBilling#27]
I'm trying to use this in a live project, and Amazon is saying it's not 64bit compliant and I think it's because of this dll.

Where did it come from? Is it possible to make a 64bit version?

**Comment by shimfish** [comment]
I see libAmazonIapV2Bridge.so is not in the arm64-v8a folder of the final apk

**Comment by shimfish** [comment]
OK. Finally worked out that there is a newer version of the Amazon IAP SDK.

For anyone interested, I've rewritten the Amazon XFInAppBillingImplementation to use the new version of the SDK.

You can then use the new Amazon bindings instead of the linked libAmazonIapV2Bridge.so, eg:
https://github.com/DevEddy/AmazonAppStoreSdkAndroidBinding

[InAppBillingImplementationAmazon.cs.txt](https://github.com/EmilAlipiev/XFInAppBilling/files/14054120/InAppBillingImplementationAmazon.cs.txt)

**Comment by EmilAlipiev** [comment]
Sounds great thanks for sharing. i will update it for maui anyone. will use yours.

**Comment by shimfish** [comment]
Great. Just double check how listeners are handled. I copied the style of the existing code and check the requestid is the same and then "deregister" the listener. However, the new SDK only allows for one listener object for everything, so I suspect this approach is wrong and could break if multiple requests are queued.
