### ISSUE TITLE
GetProductsAsync raises "Method not found" exception

### ISSUE THREAD

**Issue by StoatsOnAPlane** [EmilAlipiev/XFInAppBilling#4]
Cool package!

When I call GetProductsAsync in my android app, I get the following error:
`System.MissingMethodException: 'Method not found: void Android.BillingClient.Api.BillingClient.QuerySkuDetailsAsync(Android.BillingClient.Api.SkuDetailsParams,Android.BillingClient.Api.ISkuDetailsResponseListener)'`

That's on line 74 from here: https://github.com/EmilAlipiev/XFInAppBilling/blob/master/XFInAppBilling/XFInAppBilling.android.cs

No idea why the method would be missing. GetPurchasesAsync seems to work fine.  This is in debug mode

I'm using XFInAppBilling version 1.0.0.5 and Xamarin.Android.Google.BillingClient version 2.2.1

**Comment by StoatsOnAPlane** [comment]
looks like QuerySkuDetailsAsync only takes a single argument in the latest version

**Comment by EmilAlipiev** [comment]
yes, Xamarin published a new version 2.2.1 with Android X for compatibility and probably they reduced the parameters.  I will try to upgrade 2.2.1. in mean time you can downgrade to 2.0.3 which is 1 previous version. There is no major changes between those 2 versions when i see the history on Xamarin github. They only upgraded for Android X. 
You dont have to directly install Xamarin.Android.Google.BillingClient anyway :)

**Comment by StoatsOnAPlane** [comment]
Thanks for the response!  Very nice wrapper you've made.

**Comment by EmilAlipiev** [comment]
I have pushed a new version 2.0.0-beta. It is upgraded to use latest 2.2.1 of BillingClient
But make sure that you are use AndroidX libraries because 2.2.1 version uses AndroidX.
i havent tested each functions yet. thats why it is beta but they should be working as i didnt change any logic.
