### ISSUE TITLE
What is the difference between this lib and InAppBillingPlugin lib

### ISSUE THREAD

**Issue by Nerves82** [EmilAlipiev/XFInAppBilling#6]
This lib seems very similar to the InAppBillingPlugin by James Montemagno, are their differences or improvements made over that lib?  Can that be outlined in the readme?

https://github.com/jamesmontemagno/InAppBillingPlugin

**Comment by EmilAlipiev** [comment]
When i started this library James library was using old api of Android and UWP apis.  This uses billingclient api of Android and StoreContext from UWP and up to date with the latest versions and functionality. IOS has no difference so far. I took over the IOS code from him. It supports also Amazon iap as i wrote in the read me. you need to do a manual work if you want to use Amazon Iap as well. I want to add also Tizen soon but so far i couldnt find time for it :)

**Comment by Nerves82** [comment]
Got it. Thanks for letting me know.

**Comment by EmilAlipiev** [comment]
If you are targeting AndroidX libraries and Android 10 api version, you can use 2.2.1-pre which is using BillingClient 2.2.1. It is just called pre for precaution but actually fully tested. I am using in my projects in production.  It looks like that Xamarin has updated to 3.0 latest version 2 days ag. i will update it as well soon.

https://www.nuget.org/packages/Xamarin.Android.Google.BillingClient/3.0.0
