### ISSUE TITLE
Question - Store Purchased Application

### ISSUE THREAD

**Issue by Orgbrat** [EmilAlipiev/XFInAppBilling#7]
If an application is purchased in the Google Play Store, can XFInAppBilling be used to get the PurchaseToken and DeveloperPayload so that you may check Subscription info if purchased? I believe I have Apple figured out by using NSBundle.

Orgbrat

**Comment by EmilAlipiev** [comment]
What do you mean by application? you mean in app purchase? DeveloperPayload is deprecated by Google in the latest version. not used anymore. PurchaseToken can be retrieved  after purchase is completed and getpurchases and purchasehistory returns the token as well. you can see it here https://github.com/EmilAlipiev/XFInAppBilling/blob/master/XFInAppBilling/XFInAppBilling.android.cs

**Comment by Orgbrat** [comment]
@EmilAlipiev  Thanks for the quick reply. I did not want to perform any InApp purchases from within the app. I wanted the users to make all their purchases in the actual stores. I just wanted to query the stores for purchase info specifically subscription expiration. I was hoping to setup a renewable annual subscription and a lifetime/pay one time subscription for the application.

**Comment by EmilAlipiev** [comment]
as i said you can use getpurchases and purchasehistory. They serve on different purpose though. you can read them on Google's docs. Library implements both according to the googles docs.
